apiVersion: v1
kind: Namespace
metadata:
  name: chess-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chess-namespace
  name: chess-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chess
  template:
    metadata:
      labels:
        app: chess
    spec:
      containers:
      - name: chess
        image: junny27/chess:latest
        ports:
        - containerPort: 3000  # Assuming the Chess app runs on port 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: chess-namespace
  name: chess-service
spec:
  selector:
    app: chess
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: chess-namespace
  name: chess-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Adjust according to your ingress controller
spec:
  rules:
    - host: chess.example.com  # Replace with your domain or IP
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: chess-service
              port:
                number: 3000
