apiVersion: v1
kind: Namespace
metadata:
  name: chess-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chess-deployment
  name: chess-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chess
  template:
    metadata:
      labels:
        app: chess
    spec:
      containers:
      - name: chess
        image: junny27/chess:latest
        ports:
        - containerPort: 3000  # Assuming the Chess app runs on port 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: chess-deployment
  name: chess-service
spec:
  selector:
    app: chess
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: chess-deployment
  name: chess-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chess-service
            port:
              number: 3000
