apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chess
  template:
    metadata:
      labels:
        app: chess
    spec:
      containers:
      - name: chess
        image: junny27/chess:latest
        ports:
        - containerPort: 3000  # Assuming the Chess app runs on port 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chess-service
spec:
  selector:
    app: chess
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
