name: Build

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable debug
        run: set -x

      # Set image tags (Docker Hub username and commit SHA)
      - name: Set image tags
        id: vars
        run: |
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/chess-app
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      # Build the Docker image with both latest and commit SHA tags
      - name: Build image
        run: docker build . -t ${{ env.IMAGE_TAG }}:latest -t ${{ env.IMAGE_TAG }}:${{ env.COMMIT_SHA }}

      # Log in to Docker Hub
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Check if the latest tag exists
      - name: Check if latest exists
        id: check_latest
        run: |
          if docker pull ${{ env.IMAGE_TAG }}:latest; then
            echo "Latest tag exists."
            echo "LATEST_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Latest tag does not exist."
            echo "LATEST_EXISTS=false" >> $GITHUB_ENV
          fi

      # Conditional push based on the existence of the latest tag
      - name: Push image
        run: |
          if [ "${{ env.LATEST_EXISTS }}" = "false" ]; then
            echo "Pushing only latest tag."
            docker push ${{ env.IMAGE_TAG }}:latest
          else
            echo "Pushing commit SHA tags."
            docker push ${{ env.IMAGE_TAG }}:${{ env.COMMIT_SHA }}
          fi
