name: Build

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable debug
        run: set -x

      # Set image tags (Docker Hub username and commit SHA)
      - name: Set image tags
        id: vars
        run: |
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/actions
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)  # Shorten the commit SHA
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      # Build the Docker image with both latest and commit SHA tags
      - name: Build image
        run: docker build . -t ${{ env.IMAGE_TAG }}:latest -t ${{ env.IMAGE_TAG }}:${{ env.COMMIT_SHA }}

      # Log in to Docker Hub
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Push both tags: latest and commit SHA
      - name: Push image
        run: |
          docker push ${{ env.IMAGE_TAG }}:latest
          docker push ${{ env.IMAGE_TAG }}:${{ env.COMMIT_SHA }}
